### ISSUE TITLE
Issue #01 - Wiki Home Page

### ISSUE THREAD

**Issue by keginzburg** [junjiequ1459/fullstackProject#1]
# Wiki Home Page
- [X] Is the first page you see upon entering the wiki
- [X] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
  - [x] each wiki page is listed in bullet points
  - [x] all links route the correct page

## Comments
1. ~~Hey Rex, your Home Page needs some work. As of now, you currently have your Feature List living in the Wiki Home Page; that needs to be in its own separate Feature List page within your Wiki.~~
2. ~~Additionally, there are not side links or individual links within your Home Page right now. If you need an example for how to structure this, I recommend you utilize the [Bluebird Wiki](https://github.com/appacademy/bluebird/wiki) as a guide. Be sure to format it with markdown appropriately.~~
3. Last, be sure to add a live link to your hosted project. As we haven't begun hosting on Render yet, a placeholder link works fine for the time being.

**Comment by junjiequ1459** [comment]
Created dummy link and added bullet points
