### ISSUE TITLE
Issue #02 - Feature List

### ISSUE THREAD

**Issue by keginzburg** [junjiequ1459/fullstackProject#2]
# MVP List
- [X] Should have 7 MVPs.
  - [X] 3 of those are User Auth, Heroku, and Production README.
  - [x] The other 4 are from the [Approved Apps List](https://github.com/appacademy/cohort-resources/blob/master/full_stack_projects/aa_approved_full_stack_projects.md) or your PM will have clarified them with you
- [X] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [X] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
  - [x] MVPs are listed in an ordered list
  - [x] Each MVP is broken down into bullet points

## Comments
1. ~~Hey Rex, some work needed here as well. Your current Feature List is being hosted on your Wiki's Home Page. First, you'll need to give this its own page in your Wiki. Again, I recommend looking to the [Bluebird Wiki](https://github.com/appacademy/bluebird/wiki) as a guide.~~
2. ~~After that, your Feature List needs some serious work. Right now, I need a lot more information for each Feature. I'd like to see more thought and effort on these. I can provide an example. Currently, your Maps API feature lists that you'll be implementing an ***integration of Google Maps functionality***. Before that, there's a mention of the Yelp API (which I don't recommend you use) because you should be experiencing the practice of seeding your own data. What I'd expect to see is more along the lines of:~~
+ Seeded businesses will be rendered on Google Map API element.
+ User will be able to interact with the API to pull up a business' show page and zoom in and out of the map.
+ User will not be required to sign in/up before using the Map feature.
~~Hope this gives a more concrete idea.~~
3. ~~For your User Auth MVP, that should unofficially include your Splash Page as that will offer your users a chance to Sign Up or Login. I would also make a note that on unsuccessful sign up or login, errors will be rendered.~~
4. Tagging onto your current Features, I'm happy with **Reviews/Ratings**, **Search**, and the **Google Maps API** as Features, but I would recommend **Business Index/Show** to be your 1st Feature. **Profile Page/Saved Restaurants** feels more like a Bonus, which should be listed below your first 7 Features.
5. ~~Also, your estimated time is only accounting for User Auth right now. You should seriously consider how much time it will take to implement each Feature. Is it CRUD and therefore will it take more time? Is it an API I have no experience with, so will I take some time researching it?~~

Please let me know once you have implemented these corrections/additions. Thanks.

**Comment by keginzburg** [comment]
Hey Rex, please revisit my above Issue. You still need to revisit your Features. On top of that, I don't expect you to use the Yelp API to pull data. Instead, we expect you to seed the data yourself.

So, for your four Main Features, we expect: Business Index/Show, Reviews/Ratings, Search, and the Google Maps API. Then Profile as a Bonus.

**Comment by junjiequ1459** [comment]
Sounds good, POST isn't possible with the Yelp API. I plan downloading
their Dataset to seed them locally. Thanks for the reminder.
-rex
