### ISSUE TITLE
Issue #06 - Frontend Routes

### ISSUE THREAD

**Issue by keginzburg** [junjiequ1459/fullstackProject#6]
# Frontend Routes
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [X] Correctly formatted
  - [X] Routes are displayed with `inline coding text` (backticks)

## Comments
1. For your `/biz/:bizId` frontend route, the `Review_Form` component should be a `ReviewForm` component.
2. Out of curiosity, why are you planning on interpolating a business' `:bizId` into the frontend route for the `GoogleMap` component?
3. This is a solid start. Again, this document is usually variable to change, so don't be afraid to revisit it.

**Comment by junjiequ1459** [comment]
Im not 100% sure about the front end yet, i fixed the typo for review form. Will come back and review the front end once im up to it in the project
